server:
  port: '8080'
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: 'yyyy-MM-dd HH:mm:ss'
---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: '${SPRING_DATASOURCE_URL}'
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
stat-server:
  url: '${STAT_SERVER_URL}'
logging:
  level:
    org:
      zalando:
        logbook: TRACE
---
spring:
  config:
    activate:
      on-profile: 'ci,test'
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:exploreWithMe;MODE=PostgreSQL;'
    username: test
    password: test
stat-server:
  url: 'http://localhost:9090'
logging:
  level:
    org:
      zalando:
        logbook: TRACE

